Reading image data will be read as an array



In [4]:
import numpy as np

In [1]:
my_list = [1, 2, 3, 4, 5]

In [2]:
type(my_list)

list

it is a list type, different


In [5]:
array = np.array(my_list)

In [6]:
type(array)

numpy.ndarray

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
#3d array

np.zeros(shape=(5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros(shape=(10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

by default np.zeroes creates floats

In [11]:
np.ones(shape=(2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

will make sense as soon as it is used with images
np.zeros and np.ones to be used frequently

In [14]:
np.random.seed(37) # seed for reproducibility
arr = np.random.randint(0, 100, 10) # 10 random numbers between 0 and 100
print (arr)

[15 76 92 53 22 35 67 42 85 63]


In [15]:
arr2 = np.random.randint(0, 100, 10)
arr2

array([88, 87, 95, 62,  8,  3, 50, 76, 88, 46])

In [16]:
arr.max()   # max value in the array

92

In [17]:
arr.argmax()    #index of max value

2

In [18]:
arr.min()   # min value in the array


15

In [19]:
arr.argmin()    #index of min value 

0

In [20]:
arr.mean()  #mean of the array  

55.0

In [22]:
arr.reshape(2, 5)   #reshaping the array

array([[15, 76, 92, 53, 22],
       [35, 67, 42, 85, 63]])

In [23]:
mat = np.arange(0, 100).reshape(10, 10)

In [24]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
mat.shape

(10, 10)

In [27]:
row = 5
col = 5

mat[row, col]

55

In [29]:
#get 46 from the matrix
mat[4, 6]

46

In [30]:
#slicing the matrix 
mat[:, 1]   #get all the rows and 1st column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [36]:
#slicing multiple rows and columns
mat[0:3, 4:7]  #get 0 to 3 rows and 4 to 7 columns


array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])